{% set name = "iosacal" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/iosacal-{{ version }}.tar.gz
  sha256: be4a9523f3a498cfc69deef9e0d921bdc0fda1cdf990995b9a392623718c13d0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - "iosacal = iosacal.cli:main"

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy >=1.18.0
    - scipy >=1.1.0
    - matplotlib-base >=3.0,<4.dev0
    - click >=8.0,<9.dev0

test:
  imports:
    - iosacal
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://c14.iosa.it
  summary: IOSACal is a radiocarbon (14C) calibration program
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - steko
